name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          version:  16.15.1

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Clean install dependencies
        run: npm ci

      - name: Build Jigsaw
        run: composer install

      - name: Build app
        run: npm run prod

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build_production