name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  16.15.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Checkout branch
        uses: actions/checkout@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Clean install dependencies
        run: npm ci
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build Jigsaw
        run: composer install

      - name: Build app
        run: npm run prod
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build_production
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'